# SwiftLint Configuration for WebVideoAnalyzer
# This configuration enforces high-quality Swift code following best practices

included:
  - Sources
  - Tests

# MARK: - Code Organization Rules
documented_api:
  exempted: ["private"]

force_unwrapping:
  severity: warning

# MARK: - Architecture Enforcement Rules
large_tuple:
  warning: 3
  error: 4

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 400
  error: 600

function_body_length:
  warning: 50
  error: 100

# MARK: - Protocol-Oriented Programming Rules
single_test_class:
  severity: error

# MARK: - Swift 6.2 Compatibility
reporter: "xcode"

# MARK: - Naming Conventions
identifier_name:
  min_length:
    error: 3
  max_length:
    warning: 40
    error: 50
  excluded: ["id", "URL", "x", "y", "i"]

private_outlet:
  regex: "^(_)?[a-z][A-Za-z0-9]*$

# MARK: - Code Style Rules
line_length:
  warning: 120
  error: 150

trailing_whitespace:
  severity: warning

vertical_whitespace:
  max_empty_lines: 2
  severity: warning

# MARK: - Performance Optimization
empty_count:
  severity: warning

contains_over_first_not_nil:
  severity: warning

# MARK: - Error Handling Rules
force_try:
  severity: error

# MARK: - Type Safety
array_init:
  severity: warning

# MARK: - MVVM Architecture Support
# These rules help maintain separation of concerns in MVVM
cyclomatic_complexity:
  warning: 10
  error: 15

# MARK: - Testing Framework Rules
test_case_accessibility:
  severity: warning

# MARK: - Disabling certain rules that might conflict with our patterns
# Uncomment and modify as needed
#
# disabled_rules:
#   - colon
#   - comma
#   - control_statement
